### ISSUE TITLE
console error due to duplicate xss response headers

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/track-web#113]
![image](https://user-images.githubusercontent.com/17616596/50640357-a6a31d80-0f32-11e9-9d26-4ce1e9660f79.png)

The headers are being returned both from track-web and the hosting web services. Remove from track-web.

**Comment by timarney** [comment]
Steps to reproduce (i.e. what page)?

**Comment by obrien-j** [comment]
Fixed in #114
