### ISSUE TITLE
Forks are sending analytics to the CDS/OCIO GA tracking ID 

### ISSUE THREAD

**Issue by sidewalkballet** [cds-snc/track-web#120]
@lchski found that forked instances of the app were sending analytics back to the CDS Google Analytics account - we should remove the GA ID from the repo and include it in the deploy, if possible, so forks don't inadvertently send stats to the GC. 

https://github.com/cds-snc/track-web/blob/cff602f9728dfa0ce06352116f8e870de5a0d94f/track/templates/includes/head.html#L26

**Comment by obrien-j** [comment]
Fixed.
