### ISSUE TITLE
Live count of domains recently scanned via query, for use in the Guidance page.

### ISSUE THREAD

**Issue by buckley-w-david** [cds-snc/track-web#4]
in the "Domains measured" section of the Guidance page, it'd be nice if the number could be generated from a simple query to the datastore, as well as perhaps a most recent scan time.

Scan time may be less necessary if we move to a realtime scanning engine.

(From https://github.com/cds-snc/pulse/issues/82)

**Comment by sidewalkballet** [comment]
Closing, Guidance page doesn't include this content anymore.
