### ISSUE TITLE
Close modal by clicking off?

### ISSUE THREAD

**Issue by buckley-w-david** [cds-snc/track-web#7]
Is it possible to close the modal by clicking in the grey space around it, rather than having to click the `x`? When you scroll down inside the modal the `x` goes away and the user could miss it.

Alternate - keep `x` visible on the modal at all times.

(From https://github.com/cds-snc/pulse/issues/148)

**Comment by evadb** [comment]
This isn't actually considered proper modal behaviour. WCAG recommends modals be closable via clicking a button/symbol or pressing the esc button. Instead I'd recommend adding a "close modal" button to the bottom of it to avoid the scrolling issue or having a stick (X) symbol. I'll ask @samsadasivan which is preferred.

**Comment by buckley-w-david** [comment]
@evadb with #33 in this is fixed, correct?

**Comment by evadb** [comment]
@buckley-w-david yup! Just wanted to wait till I merged before closing :D
