### ISSUE TITLE
Screenshot in the README?

### ISSUE THREAD

**Issue by konklone** [cds-snc/track-web#70]
Since the dashboard isn't public right now and doesn't have a public URL, it could help communicate more clearly what the project is about to have a screenshot or two in the README.

**Comment by sidewalkballet** [comment]
👍good idea - I'm always wanting for more screenshots.

**Comment by sidewalkballet** [comment]
Addressed in #73, closing.

**Comment by konklone** [comment]
Nice! And thanks =)
