### ISSUE TITLE
Add HTTP response headers

### ISSUE THREAD

**Issue by damcom-gc** [cds-snc/track-web#76]
HTTP response headers that can increase the security of your application, and make the noise in a scan go away.

Add HTTP response headers
- X-Frame-Options
- X-XSS-Protection
- X-Content-Type-Options

Removed: 
- Subresource integrity 
- Content-Security-Policy (there is a much better way of doing this then what was proposed - will delay for now)

**Comment by konklone** [comment]
I've never used GTM myself, but can SRI protect against a GTM compromise? Does it only download one JS file, which is guaranteed [by Google] to remain static unless you make changes yourself to the GTM container?

**Comment by damcom-gc** [comment]
GTM is a JavaScript injection framework. I definitely could understand it better. I think the answer to your question is yes, when used with a strict CSP. I took out the SRI and the non strict CSP for now. Only including the X-Frame-Options, X-XSS-Protection, X-Content-Type-Options.

Leaving a few references for next go:
- https://csp.withgoogle.com/docs/strict-csp.html
- https://csp-evaluator.withgoogle.com/
- https://www.srihash.org/
- https://www.w3.org/TR/SRI/
