### ISSUE TITLE
Rework cache functionality to remove need for RW api keys to datastore.

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/track-web#99]
There's not really a need for write access other than a single set-cache function, suggest we just refactor this to clean this up. It's not an overly stable pattern if we were to scale out the web front end either.

This will require a couple of minor changes here and in tracker.

**Comment by sayaHub** [comment]
@obrien-j we are using right now the R/O key on our dev server .... so far so good :)

We will push the master branch when we are ready to go LIVE.

**Comment by obrien-j** [comment]
Closing this as it's been tested.
